### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating NUmpy array

In [1]:
import numpy as np

In [2]:
# one dim array 
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [3]:
# 2-Dim array 
b = np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [4]:
# 3-Dim metrices 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
type(c)
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype

d = np.array([1,2,3],dtype=bool)
print(d)

[ True  True  True]


In [6]:
# arange
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# reshape
e = np.arange(10).reshape(2,5)
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
# ones and zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# eye or identity
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# random
np.random.random((3,4))

array([[0.91459593, 0.2295899 , 0.99200204, 0.56081987],
       [0.75099409, 0.18541459, 0.95404927, 0.98256523],
       [0.18970939, 0.34053417, 0.86068612, 0.13578411]])

In [12]:
# np.linspace
np.linspace(10,-10)

array([ 10.        ,   9.59183673,   9.18367347,   8.7755102 ,
         8.36734694,   7.95918367,   7.55102041,   7.14285714,
         6.73469388,   6.32653061,   5.91836735,   5.51020408,
         5.10204082,   4.69387755,   4.28571429,   3.87755102,
         3.46938776,   3.06122449,   2.65306122,   2.24489796,
         1.83673469,   1.42857143,   1.02040816,   0.6122449 ,
         0.20408163,  -0.20408163,  -0.6122449 ,  -1.02040816,
        -1.42857143,  -1.83673469,  -2.24489796,  -2.65306122,
        -3.06122449,  -3.46938776,  -3.87755102,  -4.28571429,
        -4.69387755,  -5.10204082,  -5.51020408,  -5.91836735,
        -6.32653061,  -6.73469388,  -7.14285714,  -7.55102041,
        -7.95918367,  -8.36734694,  -8.7755102 ,  -9.18367347,
        -9.59183673, -10.        ])

### Array Attributes

In [13]:
a1 = np.arange(10,dtype='int32')
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 =  np.arange(8).reshape(2,2,2)

In [14]:
a1.ndim

1

In [15]:
a1.shape

(10,)

In [16]:
a1.size

10

In [17]:
a1.itemsize # it returns bytes

4

### changing datatypes

In [18]:
a1.astype('int8') # np.int32 == 'int8'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

### Array Operations

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [20]:
# scaler operation 
a1*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [21]:
a1 ** 3 # all arithmetic operations work

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [22]:
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
# vector operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array functions

In [24]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [25]:
a1

array([[86., 60., 68.],
       [46., 24., 66.],
       [75., 98.,  6.]])

In [28]:
# min/max/sum/prod

np.max(a1)

np.float64(98.0)

In [29]:
np.min(a1) # 0 = columns, 1= row

np.float64(6.0)

In [30]:
np.sum(a1)

np.float64(529.0)

In [31]:
a1.sum()

np.float64(529.0)

In [33]:
np.prod(a1,axis=0)

array([296700., 141120.,  26928.])

In [34]:
# mean/median /std/ var

np.mean(a1)

np.float64(58.77777777777778)

In [35]:
np.median(a1)

np.float64(66.0)

In [36]:
np.std(a1)

np.float64(27.567201839939262)

In [37]:
np.var(a1)

np.float64(759.9506172839506)

In [39]:
# trigonometric function

np.sin(a1)

array([[-0.92345845, -0.30481062, -0.89792768],
       [ 0.90178835, -0.90557836, -0.02655115],
       [-0.38778164, -0.57338187, -0.2794155 ]])

In [40]:
# dot product 
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [41]:
# log and exponents
np.exp(a1)

array([[2.23524660e+37, 1.14200739e+26, 3.40427605e+29],
       [9.49611942e+19, 2.64891221e+10, 4.60718663e+28],
       [3.73324200e+32, 3.63797095e+42, 4.03428793e+02]])

In [45]:
temp = a1*100
np.log(temp)

array([[9.05951748, 8.69951475, 8.82467789],
       [8.43381158, 7.78322402, 8.79482493],
       [8.9226583 , 9.19013766, 6.39692966]])

In [46]:
# round / floor / ceil 
np.round(a1) 

array([[86., 60., 68.],
       [46., 24., 66.],
       [75., 98.,  6.]])

In [47]:
# ceil -> next value 
np.ceil(a1)

array([[86., 60., 68.],
       [46., 24., 66.],
       [75., 98.,  6.]])

In [48]:
# floor -> back value 
np.floor(a1)

array([[86., 60., 68.],
       [46., 24., 66.],
       [75., 98.,  6.]])

### Indexing and Slicing

In [49]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [50]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [54]:
# indexing
print(a1[-1])

9


In [55]:
# 2d
print(a2[1][-2])

6


In [56]:
print(a2[1,-2])

6


In [59]:
print(a3[1,0,-1])

5


In [60]:
print(a3[0,0,0])

0


In [62]:
# slicing

a1[2:5]

array([2, 3, 4])

In [63]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a2[0,:]

array([0, 1, 2, 3])

In [69]:
a2[0,::2]

array([0, 2])

In [72]:
# a2 -> 56 , 9 , 10

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [73]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [77]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [79]:
a2[1,0::3]

array([4, 7])

In [80]:
a2[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [81]:
a3 = np.arange(27).reshape(3,3,3)

In [82]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [84]:
a3[0,1]

array([3, 4, 5])

In [93]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [94]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [99]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshape

In [102]:
# transpose 
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [103]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [104]:
# ravel -> convert tp 1 dim
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking 

In [110]:
# horizontal 
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [111]:
# vertical
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Splitting

In [112]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [115]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]